site_name: Productive Journal
site_url: https://scondo-prof.github.io/productivejournal/
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  icon:
    logo: material/lightning-bolt
  favicon: assets/favicon.ico
  features:
    # - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.instant
    - content.code.copy
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      toggle:
        icon: material/alien
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      toggle:
        icon: material/robot
        name: Switch to light mode
  plugins:
    - search
  font:
    text: "Public Sans"
    code: "Roboto Mono"
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

nav:
  - Repo: https://github.com/scondo-prof/productiveJournal
  - Home: index.md
  - 2025/04/21 | Productive Journal: weeklyProductiveJournal/2025/4/21/dailyProgress.md
  - 2025/04/26 | Dnd Journal: dndJournal/2025/4/26/hermsJournal.md
  - 2025/04/27 | Productive Journal: weeklyProductiveJournal/2025/4/27/dailyProgress.md
  - 2025/04/28 | Productive Journal: weeklyProductiveJournal/2025/4/28/dailyProgress.md
  - 2025/04/29 | Productive Journal: weeklyProductiveJournal/2025/4/29/dailyProgress.md
  - 2025/04/30 | Productive Journal: weeklyProductiveJournal/2025/4/30/dailyProgress.md
  - 2025/05/01 | Productive Journal: weeklyProductiveJournal/2025/5/01/dailyProgress.md
  - 2025/05/03 | Dnd Journal: dndJournal/2025/5/03/hermsJournal.md
